export { default as NavBar } from './navBar/Nav';
export { default as navAside } from './AsideHome/navAside';
export { default as UserBar } from './UserBar/userBar';
export { default as AppPost } from './cardPost/post';
export { default as SearchBar } from './SearchBar/searchBar';
export { default as NavResponsive } from './navBar/navBarResponsive/NavResponsive';
export { default as Photo } from './CreatePost/inputPhoto';
export { default as Post } from './CreatePost/inputPost';
export { default as ImageLogin } from './login/imageLogin';
export { default as InputLogin } from './login/inputLogin';
export { default as FooterLogin } from './login/footerLogin';
export { default as HeaderRegister } from './Register/headerRegister';
export { default as InputsRegister } from './Register/inputsRegister';
export { default as SelectorRegister } from './Register/selectorsRegister';
export {  } from '';
export {  } from '';
export {  } from '';
export {  } from '';
export {  } from '';